### ISSUE TITLE
papers needs about 1/4 page of references to people saying "sizing is a problem"

### ISSUE THREAD

**Issue by timm** [ai-se/LOC_error2#4]
ideally a dozen papers saying that this sizing thing is a fatal flaw in cocomo, most horrid problem etc

this would be a section starting section2 called "motivation" before the current 2.2
places to start:

https://scholar.google.com/scholar?hl=en&q=%2Bproblems+++%2Bcocomo+%2Bestimating+%2Bsoftware+%2Bsize&btnG=&as_sdt=1%2C34&as_sdtp=

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%2Bproblems+++%2Bcocomo+%2Bestimating+%2Bsoftware+%2Bsize

**Comment by bigfatnoob** [comment]
Could find only 4 references citing sizing is a problem in COCOMO. Added in section 2.1.
Few other references pertaining to NON-COCOMO data are included in the latex version but commented. Can be uncommented if u feel so

**Comment by bigfatnoob** [comment]
Expand Citations 3, 19-22
